import type { SongDef } from './types';

/** Mary Had a Little Lamb: 26 syllables over four lines, a held note ending each. */
export const marySong: SongDef = {
  name: 'Mary Had a Little Lamb',
  bpm: 113,
  key: 'C',
  sections: ['Part 1', 'Part 2', 'Part 3', 'Part 4'],
  events: [
    { beat: 0, object: 'lamb_1', note: 'E5', lyric: "Ma", section: 0 },
    { beat: 1, object: 'lamb_2', note: 'D5', lyric: "ry", section: 0 },
    { beat: 2, object: 'lamb_3', note: 'C5', lyric: "had", section: 0 },
    { beat: 3, object: 'lamb_4', note: 'D5', lyric: "a", section: 0 },
    { beat: 4, object: 'lamb_5', note: 'E5', lyric: "lit", section: 0 },
    { beat: 5, object: 'lamb_6', note: 'E5', lyric: "tle", section: 0 },
    { beat: 6, object: 'lamb_7', note: 'E5', lyric: "lamb", section: 0 },
    { beat: 8.5, object: 'lamb_9', note: 'D5', lyric: "lit", section: 1 },
    { beat: 9.5, object: 'lamb_10', note: 'D5', lyric: "tle", section: 1 },
    { beat: 10.5, object: 'lamb_11', note: 'D5', lyric: "lamb", section: 1 },
    { beat: 13.5, object: 'lamb_13', note: 'E5', lyric: "lit", section: 2 },
    { beat: 14.5, object: 'lamb_14', note: 'G5', lyric: "tle", section: 2 },
    { beat: 15.5, object: 'lamb_15', note: 'G5', lyric: "lamb", section: 2 },
    { beat: 18.5, object: 'lamb_17', note: 'E5', lyric: "Ma", section: 3 },
    { beat: 19.5, object: 'lamb_18', note: 'D5', lyric: "ry", section: 3 },
    { beat: 20.5, object: 'lamb_19', note: 'C5', lyric: "had", section: 3 },
    { beat: 21.5, object: 'lamb_20', note: 'D5', lyric: "a", section: 3 },
    { beat: 22.5, object: 'lamb_21', note: 'E5', lyric: "lit", section: 3 },
    { beat: 23.5, object: 'lamb_22', note: 'E5', lyric: "tle", section: 3 },
    { beat: 24.5, object: 'lamb_23', note: 'E5', lyric: "lamb", section: 3 },
    { beat: 25.5, object: 'lamb_24', note: 'E5', lyric: "its", section: 3 },
    { beat: 26, object: 'lamb_25', note: 'D5', lyric: "fleece", section: 3 },
    { beat: 27.5, object: 'lamb_26', note: 'D5', lyric: "was", section: 3 },
    { beat: 28, object: 'lamb_27', note: 'E5', lyric: "white", section: 3 },
    { beat: 29, object: 'lamb_28', note: 'D5', lyric: "as", section: 3 },
    { beat: 30, object: 'lamb_29', note: 'C5', lyric: "snow", section: 3 },
  ],
};
